apiVersion: apps/v1
kind: Deployment
metadata:
  name: gs-spring-boot-docker1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gs-spring-boot-docker1
  template:
    metadata:
      labels:
        app: gs-spring-boot-docker1
    spec:
      containers:
      - name: gs-spring-boot-docker1
        image: kpkubetestconreg.azurecr.io/kpkubetestconreg/springdemo:1
---
apiVersion: v1
kind: Service
metadata:
  name: gs-spring-boot-docker1
spec:
  type: LoadBalancer
  selector:
    app: gs-spring-boot-docker1
  ports:
  - port: 8080
    targetPort: 8085
---
piVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nodejs-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gs-spring-boot-docker1
spec:
  hosts:
  - "*"
  gateways:
  - nodegs-spring-boot-docker1-js-gateway
  http:
  - route:
    - destination:
        host: gs-spring-boot-docker1
        subset: v1
