apiVersion: apps/v1
kind: Deployment
metadata:
  name: gs-spring-boot-docker1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gs-spring-boot-docker1
  template:
    metadata:
      labels:
        app: gs-spring-boot-docker1
    spec:
      containers:
      - name: gs-spring-boot-docker1
        image: kpkubetestconreg.azurecr.io/kpkubetestconreg/springdemo:1
---
apiVersion: v1
kind: Service
metadata:
  name: gs-spring-boot-docker1
spec:
  type: LoadBalancer
  selector:
    app: gs-spring-boot-docker1
  ports:
  - port: 8080
    targetPort: 8085
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gs-spring-boot-docker1
  namespace: ingress-basic
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:	
      paths: 
      - path: /test
        backend:
          serviceName: gs-spring-boot-docker1
          servicePort: 8080

