apiVersion: apps/v1
kind: Deployment
metadata:
  name: gs-spring-boot-docker1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gs-spring-boot-docker1
  template:
    metadata:
      labels:
        app: gs-spring-boot-docker1
    spec:
      containers:
      - name: gs-spring-boot-docker1
        image: kpkubetestconreg.azurecr.io/kpkubetestconreg/springdemo:1
---
apiVersion: v1
kind: Service
metadata:
  name: gs-spring-boot-docker1
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 25001
  selector:
    app: gs-spring-boot-docker1
